[package]
name = "rkyv_faafo"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv = { version = "0.8.10", features = ["bytecheck"] }
memmap2 = "0.9.5"
# TODO stop using bytecheck, rely on a hash
bytecheck = "0.8.1"
anyhow = "1.0.97"
uuid = "1.16.0"
